/* 
 * Universalis
 *
 * Welcome to the Universalis documentation page.  <br />  <br />  There is a rate limit of 20 req/s (40 req/s burst) on the API, and 10 req/s (20 req/s burst) on the website itself, if you're scraping instead.  The number of simultaneous connections per IP is capped to 8.    To map item IDs to item names or vice versa, use <a href=\"https://xivapi.com/docs/Search#search\">XIVAPI</a>.  In addition to XIVAPI, you can also get item ID mappings from <a href=\"https://lumina.xiv.dev/docs/intro.html\">Lumina</a>,  <a href=\"https://raw.githubusercontent.com/xivapi/ffxiv-datamining/master/csv/Item.csv\">this sheet</a>, or  <a href=\"https://raw.githubusercontent.com/ffxiv-teamcraft/ffxiv-teamcraft/master/apps/client/src/assets/data/items.json\">this</a> pre-made dump.    To get a mapping of world IDs to world names, use <a href=\"https://xivapi.com/World\">XIVAPI</a> or  <a href=\"https://github.com/xivapi/ffxiv-datamining/blob/master/csv/World.csv\">this sheet</a>.  The <code>key</code> column represents the world ID, and the <code>Name</code> column represents the world name.  Note that not all listed worlds are available to be used &#8212; many of the worlds in this sheet are test worlds,  or Korean worlds (Korea is unsupported at this time).    <br />  <br />  If you use this API heavily for your projects, please consider supporting the website on  <a href=\"https://liberapay.com/karashiiro\">Liberapay</a>, <a href=\"https://ko-fi.com/karashiiro\">Ko-fi</a>, or  <a href=\"https://patreon.com/universalis\">Patreon</a>, or making a one-time donation on  <a href=\"https://ko-fi.com/karashiiro\">Ko-fi</a>. Any support is appreciated!  
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// UserCharacterView
    /// </summary>
    [DataContract]
    public partial class UserCharacterView :  IEquatable<UserCharacterView>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserCharacterView" /> class.
        /// </summary>
        /// <param name="id">The ID of this character..</param>
        /// <param name="lodestoneID">The Lodestone ID of this character..</param>
        /// <param name="updated">The time that this character was updated, in milliseconds since the UNIX epoch..</param>
        /// <param name="name">The name of this character..</param>
        /// <param name="server">The server of this character..</param>
        /// <param name="avatar">The avatar for this character..</param>
        /// <param name="main">Whether or not this character is the user&#39;s main character..</param>
        /// <param name="confirmed">Whether or not ownership of this character has been confirmed..</param>
        public UserCharacterView(string id = default(string), string lodestoneID = default(string), string updated = default(string), string name = default(string), string server = default(string), string avatar = default(string), bool? main = default(bool?), bool? confirmed = default(bool?))
        {
            this.Id = id;
            this.LodestoneID = lodestoneID;
            this.Updated = updated;
            this.Name = name;
            this.Server = server;
            this.Avatar = avatar;
            this.Main = main;
            this.Confirmed = confirmed;
        }
        
        /// <summary>
        /// The ID of this character.
        /// </summary>
        /// <value>The ID of this character.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// The Lodestone ID of this character.
        /// </summary>
        /// <value>The Lodestone ID of this character.</value>
        [DataMember(Name="lodestoneID", EmitDefaultValue=false)]
        public string LodestoneID { get; set; }

        /// <summary>
        /// The time that this character was updated, in milliseconds since the UNIX epoch.
        /// </summary>
        /// <value>The time that this character was updated, in milliseconds since the UNIX epoch.</value>
        [DataMember(Name="updated", EmitDefaultValue=false)]
        public string Updated { get; set; }

        /// <summary>
        /// The name of this character.
        /// </summary>
        /// <value>The name of this character.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The server of this character.
        /// </summary>
        /// <value>The server of this character.</value>
        [DataMember(Name="server", EmitDefaultValue=false)]
        public string Server { get; set; }

        /// <summary>
        /// The avatar for this character.
        /// </summary>
        /// <value>The avatar for this character.</value>
        [DataMember(Name="avatar", EmitDefaultValue=false)]
        public string Avatar { get; set; }

        /// <summary>
        /// Whether or not this character is the user&#39;s main character.
        /// </summary>
        /// <value>Whether or not this character is the user&#39;s main character.</value>
        [DataMember(Name="main", EmitDefaultValue=false)]
        public bool? Main { get; set; }

        /// <summary>
        /// Whether or not ownership of this character has been confirmed.
        /// </summary>
        /// <value>Whether or not ownership of this character has been confirmed.</value>
        [DataMember(Name="confirmed", EmitDefaultValue=false)]
        public bool? Confirmed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserCharacterView {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LodestoneID: ").Append(LodestoneID).Append("\n");
            sb.Append("  Updated: ").Append(Updated).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Server: ").Append(Server).Append("\n");
            sb.Append("  Avatar: ").Append(Avatar).Append("\n");
            sb.Append("  Main: ").Append(Main).Append("\n");
            sb.Append("  Confirmed: ").Append(Confirmed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserCharacterView);
        }

        /// <summary>
        /// Returns true if UserCharacterView instances are equal
        /// </summary>
        /// <param name="input">Instance of UserCharacterView to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserCharacterView input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.LodestoneID == input.LodestoneID ||
                    (this.LodestoneID != null &&
                    this.LodestoneID.Equals(input.LodestoneID))
                ) && 
                (
                    this.Updated == input.Updated ||
                    (this.Updated != null &&
                    this.Updated.Equals(input.Updated))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Server == input.Server ||
                    (this.Server != null &&
                    this.Server.Equals(input.Server))
                ) && 
                (
                    this.Avatar == input.Avatar ||
                    (this.Avatar != null &&
                    this.Avatar.Equals(input.Avatar))
                ) && 
                (
                    this.Main == input.Main ||
                    (this.Main != null &&
                    this.Main.Equals(input.Main))
                ) && 
                (
                    this.Confirmed == input.Confirmed ||
                    (this.Confirmed != null &&
                    this.Confirmed.Equals(input.Confirmed))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.LodestoneID != null)
                    hashCode = hashCode * 59 + this.LodestoneID.GetHashCode();
                if (this.Updated != null)
                    hashCode = hashCode * 59 + this.Updated.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Server != null)
                    hashCode = hashCode * 59 + this.Server.GetHashCode();
                if (this.Avatar != null)
                    hashCode = hashCode * 59 + this.Avatar.GetHashCode();
                if (this.Main != null)
                    hashCode = hashCode * 59 + this.Main.GetHashCode();
                if (this.Confirmed != null)
                    hashCode = hashCode * 59 + this.Confirmed.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
