# coding: utf-8

# flake8: noqa
"""
    Universalis

    Welcome to the Universalis documentation page.  <br />  <br />  There is a rate limit of 20 req/s (40 req/s burst) on the API, and 10 req/s (20 req/s burst) on the website itself, if you're scraping instead.  The number of simultaneous connections per IP is capped to 8.    To map item IDs to item names or vice versa, use <a href=\"https://xivapi.com/docs/Search#search\">XIVAPI</a>.  In addition to XIVAPI, you can also get item ID mappings from <a href=\"https://lumina.xiv.dev/docs/intro.html\">Lumina</a>,  <a href=\"https://raw.githubusercontent.com/xivapi/ffxiv-datamining/master/csv/Item.csv\">this sheet</a>, or  <a href=\"https://raw.githubusercontent.com/ffxiv-teamcraft/ffxiv-teamcraft/master/apps/client/src/assets/data/items.json\">this</a> pre-made dump.    To get a mapping of world IDs to world names, use <a href=\"https://xivapi.com/World\">XIVAPI</a> or  <a href=\"https://github.com/xivapi/ffxiv-datamining/blob/master/csv/World.csv\">this sheet</a>.  The <code>key</code> column represents the world ID, and the <code>Name</code> column represents the world name.  Note that not all listed worlds are available to be used &#8212; many of the worlds in this sheet are test worlds,  or Korean worlds (Korea is unsupported at this time).    <br />  <br />  If you use this API heavily for your projects, please consider supporting the website on  <a href=\"https://liberapay.com/karashiiro\">Liberapay</a>, <a href=\"https://ko-fi.com/karashiiro\">Ko-fi</a>, or  <a href=\"https://patreon.com/universalis\">Patreon</a>, or making a one-time donation on  <a href=\"https://ko-fi.com/karashiiro\">Ko-fi</a>. Any support is appreciated!    # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.currently_shown_multi_view_v2 import CurrentlyShownMultiViewV2
from swagger_client.models.currently_shown_view import CurrentlyShownView
from swagger_client.models.discord_sso_view import DiscordSsoView
from swagger_client.models.history_multi_view_v2 import HistoryMultiViewV2
from swagger_client.models.history_view import HistoryView
from swagger_client.models.listing_view import ListingView
from swagger_client.models.materia_view import MateriaView
from swagger_client.models.minimized_sale_view import MinimizedSaleView
from swagger_client.models.problem_details import ProblemDetails
from swagger_client.models.sale_view import SaleView
from swagger_client.models.sso_view import SsoView
from swagger_client.models.user_alert_create_view import UserAlertCreateView
from swagger_client.models.user_alert_event_view import UserAlertEventView
from swagger_client.models.user_alert_view import UserAlertView
from swagger_client.models.user_character_view import UserCharacterView
from swagger_client.models.user_list_view import UserListView
from swagger_client.models.user_report_view import UserReportView
from swagger_client.models.user_retainer_view import UserRetainerView
from swagger_client.models.user_view import UserView
