# coding: utf-8

"""
    Universalis

    Welcome to the Universalis documentation page.  <br />  <br />  There is a rate limit of 20 req/s (40 req/s burst) on the API, and 10 req/s (20 req/s burst) on the website itself, if you're scraping instead.  The number of simultaneous connections per IP is capped to 8.    To map item IDs to item names or vice versa, use <a href=\"https://xivapi.com/docs/Search#search\">XIVAPI</a>.  In addition to XIVAPI, you can also get item ID mappings from <a href=\"https://lumina.xiv.dev/docs/intro.html\">Lumina</a>,  <a href=\"https://raw.githubusercontent.com/xivapi/ffxiv-datamining/master/csv/Item.csv\">this sheet</a>, or  <a href=\"https://raw.githubusercontent.com/ffxiv-teamcraft/ffxiv-teamcraft/master/apps/client/src/assets/data/items.json\">this</a> pre-made dump.    To get a mapping of world IDs to world names, use <a href=\"https://xivapi.com/World\">XIVAPI</a> or  <a href=\"https://github.com/xivapi/ffxiv-datamining/blob/master/csv/World.csv\">this sheet</a>.  The <code>key</code> column represents the world ID, and the <code>Name</code> column represents the world name.  Note that not all listed worlds are available to be used &#8212; many of the worlds in this sheet are test worlds,  or Korean worlds (Korea is unsupported at this time).    <br />  <br />  If you use this API heavily for your projects, please consider supporting the website on  <a href=\"https://liberapay.com/karashiiro\">Liberapay</a>, <a href=\"https://ko-fi.com/karashiiro\">Ko-fi</a>, or  <a href=\"https://patreon.com/universalis\">Patreon</a>, or making a one-time donation on  <a href=\"https://ko-fi.com/karashiiro\">Ko-fi</a>. Any support is appreciated!    # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class MinimizedSaleView(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hq': 'bool',
        'price_per_unit': 'int',
        'quantity': 'int',
        'timestamp': 'int',
        'world_name': 'str',
        'world_id': 'int'
    }

    attribute_map = {
        'hq': 'hq',
        'price_per_unit': 'pricePerUnit',
        'quantity': 'quantity',
        'timestamp': 'timestamp',
        'world_name': 'worldName',
        'world_id': 'worldID'
    }

    def __init__(self, hq=None, price_per_unit=None, quantity=None, timestamp=None, world_name=None, world_id=None, _configuration=None):  # noqa: E501
        """MinimizedSaleView - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._hq = None
        self._price_per_unit = None
        self._quantity = None
        self._timestamp = None
        self._world_name = None
        self._world_id = None
        self.discriminator = None

        if hq is not None:
            self.hq = hq
        if price_per_unit is not None:
            self.price_per_unit = price_per_unit
        if quantity is not None:
            self.quantity = quantity
        if timestamp is not None:
            self.timestamp = timestamp
        if world_name is not None:
            self.world_name = world_name
        if world_id is not None:
            self.world_id = world_id

    @property
    def hq(self):
        """Gets the hq of this MinimizedSaleView.  # noqa: E501

        Whether or not the item was high-quality.  # noqa: E501

        :return: The hq of this MinimizedSaleView.  # noqa: E501
        :rtype: bool
        """
        return self._hq

    @hq.setter
    def hq(self, hq):
        """Sets the hq of this MinimizedSaleView.

        Whether or not the item was high-quality.  # noqa: E501

        :param hq: The hq of this MinimizedSaleView.  # noqa: E501
        :type: bool
        """

        self._hq = hq

    @property
    def price_per_unit(self):
        """Gets the price_per_unit of this MinimizedSaleView.  # noqa: E501

        The price per unit sold.  # noqa: E501

        :return: The price_per_unit of this MinimizedSaleView.  # noqa: E501
        :rtype: int
        """
        return self._price_per_unit

    @price_per_unit.setter
    def price_per_unit(self, price_per_unit):
        """Sets the price_per_unit of this MinimizedSaleView.

        The price per unit sold.  # noqa: E501

        :param price_per_unit: The price_per_unit of this MinimizedSaleView.  # noqa: E501
        :type: int
        """

        self._price_per_unit = price_per_unit

    @property
    def quantity(self):
        """Gets the quantity of this MinimizedSaleView.  # noqa: E501

        The stack size sold.  # noqa: E501

        :return: The quantity of this MinimizedSaleView.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this MinimizedSaleView.

        The stack size sold.  # noqa: E501

        :param quantity: The quantity of this MinimizedSaleView.  # noqa: E501
        :type: int
        """

        self._quantity = quantity

    @property
    def timestamp(self):
        """Gets the timestamp of this MinimizedSaleView.  # noqa: E501

        The sale time, in seconds since the UNIX epoch.  # noqa: E501

        :return: The timestamp of this MinimizedSaleView.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this MinimizedSaleView.

        The sale time, in seconds since the UNIX epoch.  # noqa: E501

        :param timestamp: The timestamp of this MinimizedSaleView.  # noqa: E501
        :type: int
        """

        self._timestamp = timestamp

    @property
    def world_name(self):
        """Gets the world_name of this MinimizedSaleView.  # noqa: E501

        The world name, if applicable.  # noqa: E501

        :return: The world_name of this MinimizedSaleView.  # noqa: E501
        :rtype: str
        """
        return self._world_name

    @world_name.setter
    def world_name(self, world_name):
        """Sets the world_name of this MinimizedSaleView.

        The world name, if applicable.  # noqa: E501

        :param world_name: The world_name of this MinimizedSaleView.  # noqa: E501
        :type: str
        """

        self._world_name = world_name

    @property
    def world_id(self):
        """Gets the world_id of this MinimizedSaleView.  # noqa: E501

        The world ID, if applicable.  # noqa: E501

        :return: The world_id of this MinimizedSaleView.  # noqa: E501
        :rtype: int
        """
        return self._world_id

    @world_id.setter
    def world_id(self, world_id):
        """Sets the world_id of this MinimizedSaleView.

        The world ID, if applicable.  # noqa: E501

        :param world_id: The world_id of this MinimizedSaleView.  # noqa: E501
        :type: int
        """

        self._world_id = world_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MinimizedSaleView, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MinimizedSaleView):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MinimizedSaleView):
            return True

        return self.to_dict() != other.to_dict()
