# coding: utf-8

"""
    Universalis

    Welcome to the Universalis documentation page.  <br />  <br />  There is a rate limit of 20 req/s (40 req/s burst) on the API, and 10 req/s (20 req/s burst) on the website itself, if you're scraping instead.  The number of simultaneous connections per IP is capped to 8.    To map item IDs to item names or vice versa, use <a href=\"https://xivapi.com/docs/Search#search\">XIVAPI</a>.  In addition to XIVAPI, you can also get item ID mappings from <a href=\"https://lumina.xiv.dev/docs/intro.html\">Lumina</a>,  <a href=\"https://raw.githubusercontent.com/xivapi/ffxiv-datamining/master/csv/Item.csv\">this sheet</a>, or  <a href=\"https://raw.githubusercontent.com/ffxiv-teamcraft/ffxiv-teamcraft/master/apps/client/src/assets/data/items.json\">this</a> pre-made dump.    To get a mapping of world IDs to world names, use <a href=\"https://xivapi.com/World\">XIVAPI</a> or  <a href=\"https://github.com/xivapi/ffxiv-datamining/blob/master/csv/World.csv\">this sheet</a>.  The <code>key</code> column represents the world ID, and the <code>Name</code> column represents the world name.  Note that not all listed worlds are available to be used &#8212; many of the worlds in this sheet are test worlds,  or Korean worlds (Korea is unsupported at this time).    <br />  <br />  If you use this API heavily for your projects, please consider supporting the website on  <a href=\"https://liberapay.com/karashiiro\">Liberapay</a>, <a href=\"https://ko-fi.com/karashiiro\">Ko-fi</a>, or  <a href=\"https://patreon.com/universalis\">Patreon</a>, or making a one-time donation on  <a href=\"https://ko-fi.com/karashiiro\">Ko-fi</a>. Any support is appreciated!    # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class UserListView(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'created': 'str',
        'updated': 'str',
        'name': 'str',
        'item_i_ds': 'list[int]'
    }

    attribute_map = {
        'id': 'id',
        'created': 'created',
        'updated': 'updated',
        'name': 'name',
        'item_i_ds': 'itemIDs'
    }

    def __init__(self, id=None, created=None, updated=None, name=None, item_i_ds=None, _configuration=None):  # noqa: E501
        """UserListView - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._created = None
        self._updated = None
        self._name = None
        self._item_i_ds = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if created is not None:
            self.created = created
        if updated is not None:
            self.updated = updated
        if name is not None:
            self.name = name
        if item_i_ds is not None:
            self.item_i_ds = item_i_ds

    @property
    def id(self):
        """Gets the id of this UserListView.  # noqa: E501

        The list's ID.  # noqa: E501

        :return: The id of this UserListView.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserListView.

        The list's ID.  # noqa: E501

        :param id: The id of this UserListView.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def created(self):
        """Gets the created of this UserListView.  # noqa: E501

        The time that this list was created, in milliseconds since the UNIX epoch.  # noqa: E501

        :return: The created of this UserListView.  # noqa: E501
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this UserListView.

        The time that this list was created, in milliseconds since the UNIX epoch.  # noqa: E501

        :param created: The created of this UserListView.  # noqa: E501
        :type: str
        """

        self._created = created

    @property
    def updated(self):
        """Gets the updated of this UserListView.  # noqa: E501

        The time that this list was updated, in milliseconds since the UNIX epoch.  # noqa: E501

        :return: The updated of this UserListView.  # noqa: E501
        :rtype: str
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this UserListView.

        The time that this list was updated, in milliseconds since the UNIX epoch.  # noqa: E501

        :param updated: The updated of this UserListView.  # noqa: E501
        :type: str
        """

        self._updated = updated

    @property
    def name(self):
        """Gets the name of this UserListView.  # noqa: E501

        The name of this list.  # noqa: E501

        :return: The name of this UserListView.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UserListView.

        The name of this list.  # noqa: E501

        :param name: The name of this UserListView.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def item_i_ds(self):
        """Gets the item_i_ds of this UserListView.  # noqa: E501

        The IDs of the list items.  # noqa: E501

        :return: The item_i_ds of this UserListView.  # noqa: E501
        :rtype: list[int]
        """
        return self._item_i_ds

    @item_i_ds.setter
    def item_i_ds(self, item_i_ds):
        """Sets the item_i_ds of this UserListView.

        The IDs of the list items.  # noqa: E501

        :param item_i_ds: The item_i_ds of this UserListView.  # noqa: E501
        :type: list[int]
        """

        self._item_i_ds = item_i_ds

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserListView, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserListView):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserListView):
            return True

        return self.to_dict() != other.to_dict()
