# coding: utf-8

"""
    Universalis

    Welcome to the Universalis documentation page.  <br />  <br />  There is a rate limit of 20 req/s (40 req/s burst) on the API, and 10 req/s (20 req/s burst) on the website itself, if you're scraping instead.  The number of simultaneous connections per IP is capped to 8.    To map item IDs to item names or vice versa, use <a href=\"https://xivapi.com/docs/Search#search\">XIVAPI</a>.  In addition to XIVAPI, you can also get item ID mappings from <a href=\"https://lumina.xiv.dev/docs/intro.html\">Lumina</a>,  <a href=\"https://raw.githubusercontent.com/xivapi/ffxiv-datamining/master/csv/Item.csv\">this sheet</a>, or  <a href=\"https://raw.githubusercontent.com/ffxiv-teamcraft/ffxiv-teamcraft/master/apps/client/src/assets/data/items.json\">this</a> pre-made dump.    To get a mapping of world IDs to world names, use <a href=\"https://xivapi.com/World\">XIVAPI</a> or  <a href=\"https://github.com/xivapi/ffxiv-datamining/blob/master/csv/World.csv\">this sheet</a>.  The <code>key</code> column represents the world ID, and the <code>Name</code> column represents the world name.  Note that not all listed worlds are available to be used &#8212; many of the worlds in this sheet are test worlds,  or Korean worlds (Korea is unsupported at this time).    <br />  <br />  If you use this API heavily for your projects, please consider supporting the website on  <a href=\"https://liberapay.com/karashiiro\">Liberapay</a>, <a href=\"https://ko-fi.com/karashiiro\">Ko-fi</a>, or  <a href=\"https://patreon.com/universalis\">Patreon</a>, or making a one-time donation on  <a href=\"https://ko-fi.com/karashiiro\">Ko-fi</a>. Any support is appreciated!    # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class UserRetainerView(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'added': 'str',
        'updated': 'str',
        'name': 'str',
        'server': 'str',
        'avatar': 'str',
        'confirmed': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'added': 'added',
        'updated': 'updated',
        'name': 'name',
        'server': 'server',
        'avatar': 'avatar',
        'confirmed': 'confirmed'
    }

    def __init__(self, id=None, added=None, updated=None, name=None, server=None, avatar=None, confirmed=None, _configuration=None):  # noqa: E501
        """UserRetainerView - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._added = None
        self._updated = None
        self._name = None
        self._server = None
        self._avatar = None
        self._confirmed = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if added is not None:
            self.added = added
        if updated is not None:
            self.updated = updated
        if name is not None:
            self.name = name
        if server is not None:
            self.server = server
        if avatar is not None:
            self.avatar = avatar
        if confirmed is not None:
            self.confirmed = confirmed

    @property
    def id(self):
        """Gets the id of this UserRetainerView.  # noqa: E501

        The retainer's ID.  # noqa: E501

        :return: The id of this UserRetainerView.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserRetainerView.

        The retainer's ID.  # noqa: E501

        :param id: The id of this UserRetainerView.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def added(self):
        """Gets the added of this UserRetainerView.  # noqa: E501

        The time that this retainer was added, in milliseconds since the UNIX epoch.  # noqa: E501

        :return: The added of this UserRetainerView.  # noqa: E501
        :rtype: str
        """
        return self._added

    @added.setter
    def added(self, added):
        """Sets the added of this UserRetainerView.

        The time that this retainer was added, in milliseconds since the UNIX epoch.  # noqa: E501

        :param added: The added of this UserRetainerView.  # noqa: E501
        :type: str
        """

        self._added = added

    @property
    def updated(self):
        """Gets the updated of this UserRetainerView.  # noqa: E501

        The time that this retainer was updated, in milliseconds since the UNIX epoch.  # noqa: E501

        :return: The updated of this UserRetainerView.  # noqa: E501
        :rtype: str
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this UserRetainerView.

        The time that this retainer was updated, in milliseconds since the UNIX epoch.  # noqa: E501

        :param updated: The updated of this UserRetainerView.  # noqa: E501
        :type: str
        """

        self._updated = updated

    @property
    def name(self):
        """Gets the name of this UserRetainerView.  # noqa: E501

        The name of this retainer.  # noqa: E501

        :return: The name of this UserRetainerView.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UserRetainerView.

        The name of this retainer.  # noqa: E501

        :param name: The name of this UserRetainerView.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def server(self):
        """Gets the server of this UserRetainerView.  # noqa: E501

        The server of this retainer.  # noqa: E501

        :return: The server of this UserRetainerView.  # noqa: E501
        :rtype: str
        """
        return self._server

    @server.setter
    def server(self, server):
        """Sets the server of this UserRetainerView.

        The server of this retainer.  # noqa: E501

        :param server: The server of this UserRetainerView.  # noqa: E501
        :type: str
        """

        self._server = server

    @property
    def avatar(self):
        """Gets the avatar of this UserRetainerView.  # noqa: E501

        The avatar for this retainer.  # noqa: E501

        :return: The avatar of this UserRetainerView.  # noqa: E501
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this UserRetainerView.

        The avatar for this retainer.  # noqa: E501

        :param avatar: The avatar of this UserRetainerView.  # noqa: E501
        :type: str
        """

        self._avatar = avatar

    @property
    def confirmed(self):
        """Gets the confirmed of this UserRetainerView.  # noqa: E501

        Whether or not ownership of this retainer has been confirmed.  # noqa: E501

        :return: The confirmed of this UserRetainerView.  # noqa: E501
        :rtype: bool
        """
        return self._confirmed

    @confirmed.setter
    def confirmed(self, confirmed):
        """Sets the confirmed of this UserRetainerView.

        Whether or not ownership of this retainer has been confirmed.  # noqa: E501

        :param confirmed: The confirmed of this UserRetainerView.  # noqa: E501
        :type: bool
        """

        self._confirmed = confirmed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserRetainerView, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserRetainerView):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserRetainerView):
            return True

        return self.to_dict() != other.to_dict()
