// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Universalis.Application.DbAccess;

namespace Universalis.Application.Migrations.AuthenticationInfo
{
    [DbContext(typeof(AuthenticationInfoContext))]
    [Migration("20210624003235_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Universalis.Entities.Uploaders.AuthenticationInfo", b =>
                {
                    b.Property<byte>("UploadApplication")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("ApiKeySha256")
                        .HasColumnType("longtext");

                    b.HasKey("UploadApplication");

                    b.ToTable("RegisteredClients");
                });
#pragma warning restore 612, 618
        }
    }
}
