# coding: utf-8

"""
    Universalis

    Welcome to the Universalis documentation page.  <br />  <br />  There is a rate limit of 20 req/s (40 req/s burst) on the API, and 10 req/s (20 req/s burst) on the website itself, if you're scraping instead.  The number of simultaneous connections per IP is capped to 8.    To map item IDs to item names or vice versa, use <a href=\"https://xivapi.com/docs/Search#search\">XIVAPI</a>.  In addition to XIVAPI, you can also get item ID mappings from <a href=\"https://lumina.xiv.dev/docs/intro.html\">Lumina</a>,  <a href=\"https://raw.githubusercontent.com/xivapi/ffxiv-datamining/master/csv/Item.csv\">this sheet</a>, or  <a href=\"https://raw.githubusercontent.com/ffxiv-teamcraft/ffxiv-teamcraft/master/apps/client/src/assets/data/items.json\">this</a> pre-made dump.    To get a mapping of world IDs to world names, use <a href=\"https://xivapi.com/World\">XIVAPI</a> or  <a href=\"https://github.com/xivapi/ffxiv-datamining/blob/master/csv/World.csv\">this sheet</a>.  The <code>key</code> column represents the world ID, and the <code>Name</code> column represents the world name.  Note that not all listed worlds are available to be used &#8212; many of the worlds in this sheet are test worlds,  or Korean worlds (Korea is unsupported at this time).    <br />  <br />  If you use this API heavily for your projects, please consider supporting the website on  <a href=\"https://liberapay.com/karashiiro\">Liberapay</a>, <a href=\"https://ko-fi.com/karashiiro\">Ko-fi</a>, or  <a href=\"https://patreon.com/universalis\">Patreon</a>, or making a one-time donation on  <a href=\"https://ko-fi.com/karashiiro\">Ko-fi</a>. Any support is appreciated!    # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]
    

setup(
    name=NAME,
    version=VERSION,
    description="Universalis",
    author_email="",
    url="",
    keywords=["Swagger", "Universalis"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Welcome to the Universalis documentation page.  &lt;br /&gt;  &lt;br /&gt;  There is a rate limit of 20 req/s (40 req/s burst) on the API, and 10 req/s (20 req/s burst) on the website itself, if you&#39;re scraping instead.  The number of simultaneous connections per IP is capped to 8.    To map item IDs to item names or vice versa, use &lt;a href&#x3D;\&quot;https://xivapi.com/docs/Search#search\&quot;&gt;XIVAPI&lt;/a&gt;.  In addition to XIVAPI, you can also get item ID mappings from &lt;a href&#x3D;\&quot;https://lumina.xiv.dev/docs/intro.html\&quot;&gt;Lumina&lt;/a&gt;,  &lt;a href&#x3D;\&quot;https://raw.githubusercontent.com/xivapi/ffxiv-datamining/master/csv/Item.csv\&quot;&gt;this sheet&lt;/a&gt;, or  &lt;a href&#x3D;\&quot;https://raw.githubusercontent.com/ffxiv-teamcraft/ffxiv-teamcraft/master/apps/client/src/assets/data/items.json\&quot;&gt;this&lt;/a&gt; pre-made dump.    To get a mapping of world IDs to world names, use &lt;a href&#x3D;\&quot;https://xivapi.com/World\&quot;&gt;XIVAPI&lt;/a&gt; or  &lt;a href&#x3D;\&quot;https://github.com/xivapi/ffxiv-datamining/blob/master/csv/World.csv\&quot;&gt;this sheet&lt;/a&gt;.  The &lt;code&gt;key&lt;/code&gt; column represents the world ID, and the &lt;code&gt;Name&lt;/code&gt; column represents the world name.  Note that not all listed worlds are available to be used &amp;#8212; many of the worlds in this sheet are test worlds,  or Korean worlds (Korea is unsupported at this time).    &lt;br /&gt;  &lt;br /&gt;  If you use this API heavily for your projects, please consider supporting the website on  &lt;a href&#x3D;\&quot;https://liberapay.com/karashiiro\&quot;&gt;Liberapay&lt;/a&gt;, &lt;a href&#x3D;\&quot;https://ko-fi.com/karashiiro\&quot;&gt;Ko-fi&lt;/a&gt;, or  &lt;a href&#x3D;\&quot;https://patreon.com/universalis\&quot;&gt;Patreon&lt;/a&gt;, or making a one-time donation on  &lt;a href&#x3D;\&quot;https://ko-fi.com/karashiiro\&quot;&gt;Ko-fi&lt;/a&gt;. Any support is appreciated!    # noqa: E501
    """
)
