// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Universalis.Application.DbAccess;

namespace Universalis.Application.Migrations.CurrentlyShown
{
    [DbContext(typeof(CurrentlyShownContext))]
    partial class CurrentlyShownContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Universalis.Entities.MarketBoard.CurrentlyShown", b =>
                {
                    b.Property<uint>("ItemId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("WorldId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("UploadApplication")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("UploaderIdHash")
                        .HasColumnType("longtext");

                    b.HasKey("ItemId", "WorldId");

                    b.ToTable("CurrentlyShownData");
                });

            modelBuilder.Entity("Universalis.Entities.MarketBoard.Listing", b =>
                {
                    b.Property<string>("InternalId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatorId")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatorName")
                        .HasColumnType("longtext");

                    b.Property<uint?>("CurrentlyShownItemId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("CurrentlyShownWorldId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Dye")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("Hq")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCrafted")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("LastReviewTime")
                        .HasColumnType("int unsigned");

                    b.Property<string>("ListingId")
                        .HasColumnType("longtext");

                    b.Property<uint>("PricePerUnit")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Quantity")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("RetainerCity")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("RetainerId")
                        .HasColumnType("longtext");

                    b.Property<string>("RetainerName")
                        .HasColumnType("longtext");

                    b.HasKey("InternalId");

                    b.HasIndex("CurrentlyShownItemId", "CurrentlyShownWorldId");

                    b.ToTable("Listing");
                });

            modelBuilder.Entity("Universalis.Entities.MarketBoard.Sale", b =>
                {
                    b.Property<string>("InternalId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BuyerName")
                        .HasColumnType("longtext");

                    b.Property<uint?>("CurrentlyShownItemId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("CurrentlyShownWorldId")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("Hq")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OnMannequin")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("PricePerUnit")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Quantity")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Timestamp")
                        .HasColumnType("int unsigned");

                    b.HasKey("InternalId");

                    b.HasIndex("CurrentlyShownItemId", "CurrentlyShownWorldId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("Universalis.Entities.Materia", b =>
                {
                    b.Property<string>("InternalId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ListingInternalId")
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("MateriaId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("SlotId")
                        .HasColumnType("int unsigned");

                    b.HasKey("InternalId");

                    b.HasIndex("ListingInternalId");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("Universalis.Entities.MarketBoard.Listing", b =>
                {
                    b.HasOne("Universalis.Entities.MarketBoard.CurrentlyShown", null)
                        .WithMany("Listings")
                        .HasForeignKey("CurrentlyShownItemId", "CurrentlyShownWorldId");
                });

            modelBuilder.Entity("Universalis.Entities.MarketBoard.Sale", b =>
                {
                    b.HasOne("Universalis.Entities.MarketBoard.CurrentlyShown", null)
                        .WithMany("RecentHistory")
                        .HasForeignKey("CurrentlyShownItemId", "CurrentlyShownWorldId");
                });

            modelBuilder.Entity("Universalis.Entities.Materia", b =>
                {
                    b.HasOne("Universalis.Entities.MarketBoard.Listing", null)
                        .WithMany("Materia")
                        .HasForeignKey("ListingInternalId");
                });

            modelBuilder.Entity("Universalis.Entities.MarketBoard.CurrentlyShown", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("RecentHistory");
                });

            modelBuilder.Entity("Universalis.Entities.MarketBoard.Listing", b =>
                {
                    b.Navigation("Materia");
                });
#pragma warning restore 612, 618
        }
    }
}
