USE `dalamud`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '(DC2Type:guid)',
  `added` int(11) NOT NULL,
  `last_online` int(11) NOT NULL,
  `is_banned` tinyint(1) NOT NULL DEFAULT 0,
  `notes` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sso` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `username` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `avatar` varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `patron` int(11) NOT NULL,
  `patron_benefit_user` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `permissions` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `admin` tinyint(1) NOT NULL DEFAULT 0,
  `alerts_max` int(11) NOT NULL,
  `alerts_expiry` int(11) NOT NULL,
  `alerts_update` tinyint(1) NOT NULL,
  `sso_discord_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sso_discord_avatar` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sso_discord_token_expires` int(11) DEFAULT NULL,
  `sso_discord_token_access` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sso_discord_token_refresh` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `api_public_key` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `api_analytics_key` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `api_rate_limit` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `added` (`added`),
  KEY `sso` (`sso`),
  KEY `username` (`username`),
  KEY `email` (`email`),
  KEY `is_banned` (`is_banned`),
  KEY `api_public_key` (`api_public_key`),
  KEY `sso_discord_id` (`sso_discord_id`),
  KEY `sso_discord_avatar` (`sso_discord_avatar`),
  KEY `sso_discord_token_expires` (`sso_discord_token_expires`),
  KEY `sso_discord_token_access` (`sso_discord_token_access`),
  KEY `sso_discord_token_refresh` (`sso_discord_token_refresh`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;