USE `dalamud`;
CREATE TABLE `users_alerts` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '(DC2Type:guid)',
  `user_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '(DC2Type:guid)',
  `uniq` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `item_id` int(11) NOT NULL,
  `added` int(11) NOT NULL,
  `active_time` int(11) NOT NULL,
  `last_checked` int(11) NOT NULL DEFAULT 0,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `server` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `expiry` int(11) NOT NULL,
  `trigger_conditions` longtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '(DC2Type:array)',
  `trigger_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `trigger_last_sent` int(11) NOT NULL,
  `triggers_sent` int(11) NOT NULL,
  `trigger_action` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `trigger_data_center` tinyint(1) NOT NULL DEFAULT 0,
  `trigger_hq` tinyint(1) NOT NULL DEFAULT 0,
  `trigger_nq` tinyint(1) NOT NULL DEFAULT 0,
  `trigger_active` tinyint(1) NOT NULL DEFAULT 1,
  `notified_via_email` tinyint(1) NOT NULL DEFAULT 0,
  `notified_via_discord` tinyint(1) NOT NULL DEFAULT 0,
  `keep_updated` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_F89D4EFBACD1F8DC` (`uniq`),
  KEY `IDX_F89D4EFBA76ED395` (`user_id`),
  KEY `uniq` (`uniq`),
  KEY `item_id` (`item_id`),
  KEY `last_checked` (`last_checked`),
  KEY `server` (`server`),
  CONSTRAINT `FK_F89D4EFBA76ED395` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;